set(PROJECT_SOURCE_ROOT ${PROJECT_ROOT}/source)
set(PROJECT_QUI_ROOT ${PROJECT_SOURCE_ROOT}/UI)
set(PROJECT_WINDOW_ROOT ${PROJECT_SOURCE_ROOT}/Window)

file(GLOB PROJECT_FILES_MAIN "${PROJECT_SOURCE_ROOT}/*.*")
file(GLOB PROJECT_FILES_MATH "${PROJECT_SOURCE_ROOT}/Math/*.*")
file(GLOB PROJECT_FILES_UTIL "${PROJECT_SOURCE_ROOT}/Utils/*.*")
file(GLOB PROJECT_FILES_WINDOW "${PROJECT_SOURCE_ROOT}/Window/*.*")
file(GLOB PROJECT_FILES_RT  "${PROJECT_SOURCE_ROOT}/RayTracer/*.*")
file(GLOB PROJECT_FILES_MAT "${PROJECT_SOURCE_ROOT}/RayTracer/material/*.*")
file(GLOB PROJECT_FILES_GEO "${PROJECT_SOURCE_ROOT}/RayTracer/geometry/*.*")
file(GLOB PROJECT_FILES_QUI "${PROJECT_QUI_ROOT}/*.ui")
file(GLOB PROJECT_FILES_QRC "${PROJECT_QUI_ROOT}/*.qrc")

#SOURCE_GROUP("project\\sourceS" FILES ${PROJECT_FILES_SOURCE})

set(PROJECT_FILES_MOCCABLE
    ${PROJECT_WINDOW_ROOT}/MainWindow.h
    ${PROJECT_WINDOW_ROOT}/SlideSpinBox.h
    ${PROJECT_WINDOW_ROOT}/CustDrawWidget.h
    )

set(PROJECT_FILES_ALLRAW
    ${PROJECT_FILES_MATH}
    ${PROJECT_FILES_WINDOW}
    ${PROJECT_FILES_MAIN}
    ${PROJECT_FILES_UTIL}
    ${PROJECT_FILES_RT}
    ${PROJECT_FILES_MAT}
    ${PROJECT_FILES_GEO}
    ${PROJECT_FILES_QUI}
    ${PROJECT_FILES_QRC}
)

set(PROJECT_DIRS_INCLUDE
    ${PROJECT_SOURCE_ROOT}/Math
    ${PROJECT_SOURCE_ROOT}/RayTracer
    ${PROJECT_SOURCE_ROOT}/RayTracer/material
    ${PROJECT_SOURCE_ROOT}/RayTracer/geometry
    ${PROJECT_SOURCE_ROOT}/Utils
    ${PROJECT_SOURCE_ROOT}/Window
    )

include_directories(${PROJECT_DIRS_INCLUDE})